const express = require('express')
const app = express()
const indexRouter = require('./routes/index')
const dashboardRouter = require('./routes/dashboard')
const userRouter = require('./routes/users')
const PORT = process.env.PORT || 8000
app.use(express.json())
app.use('/',indexRouter)
app.use('/dashboard',dashboardRouter)
app.use('/users',userRouter)
app.listen(8000,()=>console.log('App running port 8000'))